name: http_errors-ci

on: [push, pull_request]

jobs:
  http_errors:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.2.0

      - run: deno --version
      - run: deno fmt --check
      - run: deno test -A

      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.4.0

      - run: deno --version
      - run: deno fmt --check
      - run: deno test -A
      - run: deno run --unstable ./test/http_errors_test.ts
